### ISSUE TITLE
NMS in DAS Module of SiamCDA

### ISSUE THREAD

**Issue by easycodesniper-afk** [RaymondCover/CHANet#1]
Hello, I've read your paper SiamCDA and I'm confused about your DAS Module.It says in paper:"Then the Non-maximum Suppression (NMS) is performed on those preserved bounding boxes to further remove those bounding boxes with smaller confidence scores".As I know NMS is a loop to remove proposals by IOU but not confidence score and those proposals of HIGH IOU with best proposal will be removed first. It seems contradictory. 
Futhermore, is NMS really valuable in SINGLE object tracking? It is always used in detection field.
Hope your reply!

**Comment by Tianlu-Zhang** [comment]
Hello, we keep the bounding box with the highest score among all proposals for each target in the implementation. The proposed module mainly plays a role in judging whether drift. The experimental results are indeed effective.

**Comment by easycodesniper-afk** [comment]
> 

RPN系列是对每个proposal打分，比如你响应图大小是21*21，共有5个不同尺度，那就是一共21*21*5总计2205个候选框，选最终结果的时候是对这2205个候选框置信度进行排序，选置信度最高的；所以它对相似目标表现不好，有可能相似目标相对于真值置信度更高，就会出现预测错框的情况，而nms每一轮过程实际上是选出候选框集合里置信度最高的框，再根据剩余候选框和最高置信度框的iou是否大于阈值这个标准，抛弃高iou的框。在这一的前提下，对RPN产生的Proposal集合使用NMS有什么意义呢？最后不是还是选择了置信度最高的框吗？

**Comment by Tianlu-Zhang** [comment]
最后不是直接选择置信度最高的框，是利用NMS选出了一些潜在目标位置，再进一步判断那个候选框是目标的，建议参考文章内容。

**Comment by easycodesniper-afk** [comment]
> 最后不是直接选择置信度最高的框，是利用NMS选出了一些潜在目标位置，再进一步判断那个候选框是目标的，建议参考文章内容。

不好意思，我刚才才看到您的回复。方便的话可以加个QQ吗，我对这一块儿还是有点困惑，我的qq号是764386017
